spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdemo
    username: root
    password: root123
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # This should be handled by Flyway if you use it for schema management
      show-sql: true
    properties:
      hibernate:
       format-sql: true
       type.descriptor.sql.BasicBinder.log_bind_param: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholders:
      my_placeholder: my_value

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    io.jsonwebtoken: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
